name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 439045398889.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t django-poc . 

      - name: Tag image
        run: docker tag django-poc:latest 439045398889.dkr.ecr.ap-south-1.amazonaws.com/django-poc:latest

      - name: Push to ECR
        run: docker push 439045398889.dkr.ecr.ap-south-1.amazonaws.com/django-poc:latest

      - name: Force ECS Deployment
        run: |
          aws ecs update-service \
            --cluster django-cluster \
            --service django-task-service \
            --force-new-deployment